# Generated by Django 4.2.30 on 2026-05-02 21:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0002_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('transfer', 'Transfer'), ('damaged', 'Damaged'), ('lost', 'Lost/Stolen'), ('returned', 'Returned to Supplier'), ('expiry', 'Expired'), ('other', 'Other')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='stock_manager.item')),
                ('source_shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_transactions', to='stock_manager.shop')),
                ('target_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_transactions', to='stock_manager.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
