# Generated by Django 5.2.3 on 2026-05-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0005_meeting_userpresence_message_call_meetingparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
