# Generated by Django 5.2.3 on 2026-05-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0006_alter_item_quantity_alter_stocktransaction_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
