# Generated by Django 4.2.30 on 2026-05-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0009_businessperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodOpeningStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_stocks', to='stock_manager.businessperiod')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_manager.shop')),
            ],
            options={
                'verbose_name': 'Period Opening Stock',
                'verbose_name_plural': 'Period Opening Stocks',
                'ordering': ['item_name'],
                'unique_together': {('period', 'item_name', 'shop')},
            },
        ),
    ]
