# Generated by Django 4.2.30 on 2026-05-15 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0012_companyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('business_name', models.CharField(blank=True, default='My Business', max_length=200)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=100)),
                ('api_key', models.TextField(blank=True, default='')),
                ('greeting_message', models.TextField(blank=True, default='Hello! Welcome to our store. How can we assist you today?')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Setting',
                'verbose_name_plural': 'WhatsApp Settings',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(db_index=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('wa_message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('body', models.TextField()),
                ('is_from_customer', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_manager.whatsappmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
