# Generated by Django 4.2.30 on 2026-05-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0013_whatsappsetting_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='hero_tagline',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='hero_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
