# Generated by Django 4.2.30 on 2026-05-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0014_companyprofile_hero_tagline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Landing Page Content',
                'verbose_name_plural': 'Landing Page Content',
            },
        ),
    ]
