# Generated by Django 4.2.30 on 2026-05-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0015_landingpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='landing/'),
        ),
    ]
