# Generated by Django 6.0.5 on 2026-05-20 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0016_landingpagecontent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='stock_manager.receipt'),
        ),
    ]
