# Generated by Django 6.0.5 on 2026-05-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0020_alter_profile_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=None, help_text='List of granted permission keys. None = no extra access.', null=True),
        ),
    ]
