# Generated by Django 6.0.5 on 2026-05-22 10:25

import stock_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0024_populate_shop_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=stock_manager.models._receipt_pdf_path, verbose_name='Receipt PDF'),
        ),
    ]
