# Generated by Django 4.2.30 on 2026-05-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0028_add_profile_online_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='host',
        ),
        migrations.AlterUniqueTogether(
            name='meetingparticipant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='meetingparticipant',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='meetingparticipant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpresence',
            name='current_shop',
        ),
        migrations.RemoveField(
            model_name='userpresence',
            name='typing_to',
        ),
        migrations.RemoveField(
            model_name='userpresence',
            name='user',
        ),
        migrations.DeleteModel(
            name='Call',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.DeleteModel(
            name='MeetingParticipant',
        ),
        migrations.DeleteModel(
            name='UserPresence',
        ),
    ]
