# Generated by Django 4.2.30 on 2026-05-27 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0032_add_transfer_notification_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='stock_manager.transfer'),
        ),
    ]
