# Generated by Django 4.2.30 on 2026-05-27 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock_manager', '0033_add_stock_transaction_transfer_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessperiod',
            name='closed_by',
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
        migrations.DeleteModel(
            name='LandingPageContent',
        ),
        migrations.AlterUniqueTogether(
            name='periodopeningstock',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='periodopeningstock',
            name='period',
        ),
        migrations.RemoveField(
            model_name='periodopeningstock',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='receiptitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='receiptitem',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='transferitem',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='replied_to',
        ),
        migrations.DeleteModel(
            name='WhatsAppSetting',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='stock_manag_user_id_b8f6be_idx',
        ),
        migrations.RemoveIndex(
            model_name='transfer',
            name='stock_manag_status_cd834a_idx',
        ),
        migrations.RemoveIndex(
            model_name='transfer',
            name='stock_manag_transfe_c658ca_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_manager.shop'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_manager.item'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='target_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_manager.shop'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('damaged', 'Damaged'), ('lost', 'Lost/Stolen'), ('returned', 'Returned'), ('expiry', 'Expired'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='BusinessPeriod',
        ),
        migrations.DeleteModel(
            name='PeriodOpeningStock',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='ReceiptItem',
        ),
        migrations.DeleteModel(
            name='TransferItem',
        ),
        migrations.DeleteModel(
            name='WhatsAppMessage',
        ),
    ]
