# Generated by Django 4.2.30 on 2026-05-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0035_landingpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='items_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='transfer',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
