# Generated by Django 4.2.30 on 2026-05-28 21:55

from django.db import migrations, models
from django.db.models.fields import NOT_PROVIDED


def add_status_column(apps, schema_editor):
    table_name = 'stock_manager_message'
    column_name = 'status'
    with schema_editor.connection.cursor() as cursor:
        # Check if column already exists
        if schema_editor.connection.vendor == 'sqlite':
            cursor.execute(f'PRAGMA table_info({table_name})')
            cols = [row[1] for row in cursor.fetchall()]
            if column_name not in cols:
                cursor.execute(
                    f'ALTER TABLE {table_name} ADD COLUMN {column_name} '
                    f"varchar(20) NOT NULL DEFAULT 'sent'"
                )
        elif schema_editor.connection.vendor == 'postgresql':
            cursor.execute(f"""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = '{table_name}'
                        AND column_name = '{column_name}'
                    ) THEN
                        ALTER TABLE {table_name}
                        ADD COLUMN {column_name} varchar(20) NOT NULL DEFAULT 'sent';
                    END IF;
                END $$;
            """)
        else:
            # Fallback: try to add, ignore error if exists
            try:
                cursor.execute(
                    f'ALTER TABLE {table_name} ADD COLUMN {column_name} '
                    f"varchar(20) NOT NULL DEFAULT 'sent'"
                )
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0040_add_conversation_and_read_at'),
    ]

    operations = [
        migrations.RunPython(
            add_status_column,
            reverse_code=migrations.RunPython.noop,
            elidable=False,
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(
                choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')],
                default='sent',
                max_length=20,
            ),
            preserve_default=True,
        ),
    ]
