# Generated by Django 4.2.30 on 2026-05-29 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exports/')),
                ('filesize', models.PositiveIntegerField(default=0)),
                ('include_products', models.BooleanField(default=True)),
                ('include_categories', models.BooleanField(default=True)),
                ('include_users', models.BooleanField(default=True)),
                ('include_roles', models.BooleanField(default=True)),
                ('include_sales', models.BooleanField(default=True)),
                ('include_transactions', models.BooleanField(default=True)),
                ('include_chat', models.BooleanField(default=True)),
                ('include_notifications', models.BooleanField(default=True)),
                ('include_settings', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('add', 'Add New Records Only'), ('merge', 'Merge Existing Records'), ('replace', 'Full Replace')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preview', 'Preview Ready'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, default='')),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_migration.exportarchive')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
