# Generated by Django 4.2.30 on 2026-05-29 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('changelog', models.TextField(blank=True, default='')),
                ('is_current', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('download_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Version',
                'verbose_name_plural': 'System Versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpdateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_from', models.CharField(max_length=20)),
                ('version_to', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('changelog', models.TextField(blank=True, default='')),
                ('backup_file', models.FileField(blank=True, null=True, upload_to='backups/')),
                ('backup_size', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('installed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
